# Generated by Django 5.0 on 2023-12-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=256)),
                ("country", models.CharField(max_length=50)),
                ("airport_code", models.BigIntegerField()),
            ],
        ),
    ]
