# Generated by Django 4.2.8 on 2023-12-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avia_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airline", models.IntegerField()),
                ("date_of_journey", models.DateField()),
                ("source", models.IntegerField()),
                ("destination", models.IntegerField()),
                ("additional_info", models.CharField(max_length=256)),
                ("price", models.IntegerField()),
                ("data_source", models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name="city",
            name="airport_code",
            field=models.IntegerField(),
        ),
    ]
